service: nodejs-serverless-swapi

plugins:
  - serverless-plugin-typescript 
  - serverless-offline
	
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - ${env:ARN}
  environment: 
    NODE_ENV: ${env:NODE_ENV}
    SWAPI_URL: ${env:SWAPI_URL}
    GOOGLE_CREDENTIALS: ${env:GOOGLE_CREDENTIALS}

functions:
  getPerson:
    handler: src/handler.getPerson
    events:
      - http:
          path: person/{id}
          method: get

  getPeople:
    handler: src/handler.getPeople
    events:
      - http:
          path: people/
          method: get
          
  createSpecie:
    handler: src/handler.createSpecie
    events:
      - http:
          path: specie
          method: post
  # find:
  #   handler: app/handler.find
  #   events:
  #     - http:
  #         path: books
  #         method: get
  # findOne:
  #   handler: app/handler.findOne
  #   events:
  #     - http:
  #         path: books/{id}
  #         method: get

  # deleteOne:
  #   handler: app/handler.deleteOne
  #   events:
  #     - http:
  #         path: books/{id}
  #         method: delete

resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: {env:DYNAMODB_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH